version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "python /app/${PROJECT_NAME:-myproject}/manage.py runserver 0.0.0.0:8000"
